"""The verifier — claim-vs-contract grading + calibration."""

from .calibration import Bin, ece, pairs_from, pick_threshold, reliability_curve
from .graders import (
    AblationSignal,
    ExtractedAtom,
    GateRoute,
    claim_survives_ablation,
    extracted_claims,
    js_divergence,
    luhn_valid,
    normalize,
    route_claim,
    substring_overlap_ratio,
    token_jaccard_distinctive,
    verbatim_overlap_ratio,
    violates_declared_constraints,
)
from .schema import (
    DEFAULT_POLICY,
    DEFAULT_THRESHOLD,
    LENIENT,
    STRICT,
    ClaimVerdict,
    SettlementPolicy,
    SettlementRuling,
    Verdict,
    rule_settlement,
)
from .verifier import Verifier

__all__ = [
    "Verifier",
    "Verdict",
    "ClaimVerdict",
    "SettlementRuling",
    "rule_settlement",
    "SettlementPolicy",
    "LENIENT",
    "STRICT",
    "DEFAULT_POLICY",
    "DEFAULT_THRESHOLD",
    "reliability_curve",
    "ece",
    "pick_threshold",
    "pairs_from",
    "Bin",
    "substring_overlap_ratio",
    "verbatim_overlap_ratio",
    "token_jaccard_distinctive",
    "js_divergence",
    "extracted_claims",
    "ExtractedAtom",
    "luhn_valid",
    "violates_declared_constraints",
    "normalize",
    "claim_survives_ablation",
    "route_claim",
    "GateRoute",
    "AblationSignal",
]
